# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow requires that you have an existing account with codescan.io
# For more information about configuring your workflow,
# read our documentation at https://github.com/codescan-io/codescan-scanner-action
name: CodeScan

env:
  SONAR_SCANNER_VERSION: 5.0.1.3006
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

on:
  push:
    branches: [ "*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "*" ]

permissions:
  contents: read

jobs:
    CodeScan:
        environment: preview
        permissions:
          contents: read # for actions/checkout to fetch code
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Cache files
                uses: actions/cache@v4
                with:
                    path: |
                        ~/.sonar
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar
            -   name: Run Analysis
                if: github.event_name == 'push'
                uses: codescan-io/codescan-scanner-action@2.0
                with:
                    scanChangedFilesOnly: false
                    generateSarifFile: false
                    failOnRedQualityGate: true
                    generateReportFile: false
                    login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
                    organization: va-pr
                    projectKey: github-va-test
                    codeScanUrl: https://test.codescan.io/
                    args: |
                      sonar.branch.name=${{github.base_ref}}
                      sonar.sources=.
                      sonar.exclusions=target/**,**/*.java
                      sonar.analysisCache.enabled=false
                      codescan.suppressUnitTestViolations=false
                      sonar.verbose=true
                      sonar.scm.provider=git
                      sonar.scm.disabled=false
            -   name: Run Analysis on PR
                if: github.event_name == 'pull_request'
                uses: codescan-io/codescan-scanner-action@2.0
                with:
                    scanChangedFilesOnly: false
                    generateSarifFile: false
                    failOnRedQualityGate: true
                    generateReportFile: false
                    login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
                    organization: va-pr
                    projectKey: github-va-test
                    codeScanUrl: https://test.codescan.io/
                    args: |
                      sonar.sources=.
                      sonar.exclusions=target/**,**/*.java
                      sonar.analysisCache.enabled=false
                      codescan.suppressUnitTestViolations=false
                      sonar.verbose=true
                      sonar.pullrequest.branch=${{github.head_ref}}
                      sonar.pullrequest.base=${{github.base_ref}}
                      sonar.pullrequest.key=${{github.event.number}}
                      sonar.scm.provider=git
                      sonar.scm.disabled=false
